version: "3"

services:
  nginx-angular:
    container_name: primeweb
    build:
        context: prime-angular-frontend/
    command: "nginx -g 'daemon off;'"
    restart: always
    ports:
      - "80:80"
    expose:
      - "80"
    networks:
      - primenet